clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

variables:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -Pcicd'

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &populate-caches
        name: Populate .m2 repository-cache and sonar-cache
        image: adoptopenjdk/maven-openjdk11@sha256:fd7ca81dc66b2d42907d2259ac179058bb26d8ce909116e1a8a3b539292cc988
        caches:
          - maven
          - sonar
        script:
          - cicd/backend/unit-test-with-coverage.sh
          - cicd/backend/install.sh
          - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.java.libraries=**/*.jar
          - cicd/backend/build-uber-jars.sh
    - step: &build-java
        name: Build Java source code
        image: adoptopenjdk/maven-openjdk11@sha256:fd7ca81dc66b2d42907d2259ac179058bb26d8ce909116e1a8a3b539292cc988
        caches:
          - maven
        script:
          - cicd/backend/build.sh
        artifacts:
          - "**/target/classes/**"
          - "**/target/generated-sources/**"
          - "**/target/generated-test-sources/**"
          - "**/target/test-classes/**"
          - "**/target/maven-archiver/**"
          - "**/maven-status/**"
          - "**/target/*.jar"
    - step: &unit-test-java
        name: Execute Java unit tests
        image: adoptopenjdk/maven-openjdk11@sha256:fd7ca81dc66b2d42907d2259ac179058bb26d8ce909116e1a8a3b539292cc988
        caches:
          - maven
        script:
          - cicd/backend/unit-test.sh
    - step: &unit-test-java-coverage
        name: Exeucte Java unit tests with coverage
        image: adoptopenjdk/maven-openjdk11@sha256:fd7ca81dc66b2d42907d2259ac179058bb26d8ce909116e1a8a3b539292cc988
        caches:
          - maven
        script:
          - cicd/backend/unit-test-with-coverage.sh
        artifacts:
          - "**/jacoco.xml"
    - step: &analyze-with-sonar
        name: Analyze with Sonar
        image: adoptopenjdk/maven-openjdk11@sha256:fd7ca81dc66b2d42907d2259ac179058bb26d8ce909116e1a8a3b539292cc988
        caches:
          - maven
          - sonar
        script:
          - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.java.libraries=**/*.jar

pipelines:
  custom:
    populate-caches:
      - step: *populate-caches
  branches:
    feature/*:
      - step: *build-java
      - step: *unit-test-java
      - step:
          <<: *unit-test-java-coverage
          trigger: manual
      - step:
          <<: *analyze-with-sonar
          trigger: manual
    develop:
      - step: *build-java
      - step: *unit-test-java-coverage
      - step: *analyze-with-sonar
    master:
      - step: *build-java
      - step: *unit-test-java-coverage
      - step: *analyze-with-sonar
  pull-requests:
    "**":
      - step: *build-java
      - step: *unit-test-java-coverage
      - step: *analyze-with-sonar