quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:rpg_language}
    password: ${DB_PASSWORD:rpg_language}
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:language}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
  hibernate-orm:
    database:
      generation: none
  http:
    port: ${HTTP_PORT:8080}
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd'T'HH:mm:ss.sss}Z %p [%h@%C.%M] %m%n"
  package:
    uber-jar: true
oauth2:
  server-url: ${OAUTH2_SERVER_URL:http://localhost:8090/auth}
  realm:
    name: ${OAUTH2_REALM_NAME:test}
  admin-cli:
    id: ${OAUTH2_ADMIN_CLI_ID:admin-cli}
    secret: ${OAUTH2_ADMIN_CLI_SECRET:e436557b-2eed-4182-a928-dd370320e3ad}
  client:
    id: ${OAUTH2_CLIENT_ID:test}
    secret: ${OAUTH2_CLIENT_SECRET:cb5a84e8-a676-4610-b526-7e0c0798dc1a}
mp:
  jwt:
    verify:
      publickey:
        location: ${OAUTH2_PUBLICKEY_URL:http://localhost:8090/auth/realms/${oauth2.realm.name}/protocol/openid-connect/certs}