quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:rpg_language}
    password: ${DB_PASSWORD:rpg_language}
    jdbc:
      driver: io.opentracing.contrib.jdbc.TracingDriver
      url: jdbc:tracing:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:language}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      generation: none
  http:
    cors:
      ~: true
    port: ${HTTP_PORT:8080}
  jaeger:
    enabled: true
    endpoint: ${TRACING_ENDPOINT:http://localhost:14268/api/traces}
    sampler-type: const
    sampler-param: 1
    service-name: language-service
  oidc:
    enabled: true
    application-type: service
    auth-server-url: ${OIDC_SERVER_URL:http://localhost:8090/auth}/realms/${OIDC_REALM_NAME:test}
    client-id: ${OIDC_LANGUAGE_SERVICE_CLIENT_ID:language-service-client}
    introspection-path: /protocol/openid-connect/userinfo
    jwks-path: /protocol/openid-connect/certs
    token:
      audience: ${LANGUAGE_SERVICE_AUDIENCE:test}
      principal-claim: preferred_username
    credentials:
      secret: ${OIDC_LANGUAGE_SERVICE_CLIENT_SECRET:53574baa-7a35-4ebd-88e1-3fd258ae89c4}
  smallrye-jwt:
    enabled: false
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd'T'HH:mm:ss.sss}Z %p [%h@%C.%M] %m%n"
keycloak:
  server-url: ${OIDC_SERVER_URL:http://localhost:8090/auth}
  realm:
    name: ${OIDC_REALM_NAME:test}
  admin-cli:
    id: ${OIDC_ADMIN_CLI_ID:admin-cli}
    secret: ${OIDC_ADMIN_CLI_SECRET:e436557b-2eed-4182-a928-dd370320e3ad}
  client:
    id: ${OIDC_CLIENT_ID:test}
    secret: ${OIDC_CLIENT_SECRET:cb5a84e8-a676-4610-b526-7e0c0798dc1a}
mp:
  jwt:
    verify:
      publickey:
        location: ${OIDC_PUBLICKEY_URL:${oauth2.server-url}/realms/${oauth2.realm.name}/protocol/openid-connect/certs}