quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:rpg_user}
    password: ${DB_PASSWORD:rpg_user}
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:user}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
  hibernate-orm:
    database:
      generation: none
  http:
    cors:
      ~: true
    port: ${HTTP_PORT:8081}
  oidc:
    enabled: true
    application-type: service
    auth-server-url: ${OIDC_SERVER_URL:http://localhost:8090/auth}/realms/${OIDC_REALM_NAME:test}
    client-id: ${OIDC_USER_SERVICE_CLIENT_ID:user-service-client}
    introspection-path: /protocol/openid-connect/userinfo
    jwks-path: /protocol/openid-connect/certs
    token:
      audience: ${USER_SERVICE_AUDIENCE:test}
      principal-claim: preferred_username
    credentials:
      secret: ${OIDC_USER_SERVICE_CLIENT_SECRET:a5464cc8-9343-4e61-91b9-5547c9708902}
  smallrye-jwt:
    enabled: false
  log:
    level: TRACE
    console:
      format: "%d{yyyy-MM-dd'T'HH:mm:ss.sss}Z %p [%h@%C.%M] %m%n"
  package:
    uber-jar: true
keycloak:
  server-url: ${OIDC_SERVER_URL:http://localhost:8090/auth}
  realm-name: ${OIDC_REALM_NAME:test}
  admin-cli-id: ${OIDC_ADMIN_CLI_ID:admin-cli}
  admin-cli-secret: ${OIDC_ADMIN_CLI_SECRET:939f3082-4de8-4bfe-9008-2c6def83c72f}
microservice:
  language:
    url: ${LANGUAGE_SERVICE_URL:http://localhost:8080}

language-rest/mp-rest/url: ${microservice.language.url}
language-rest/mp-rest/scope: javax.inject.Singleton