version: "3.7"

services:
  postgres:
    image: postgres:12.2@sha256:c52d4eac43883c53113cee0ebd1ce0fe53ef0604708822901ecca6655968fa9a
    environment:
      - POSTGRES_DB=untitled_rpg
      - POSTGRES_USER=G4nd4lf
      - POSTGRES_PASSWORD=Mell0n
    ports:
      - '15432:5432'
  keycloak:
    image: jboss/keycloak:8.0.1@sha256:9a91f646de4becefbae9bd3e5e0cd8de21bf17a22055ccabff324798c2be68a0
    volumes:
      - ./test-realm.json:/tmp/test-realm.json
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_USER=5Element
      - KEYCLOAK_PASSWORD=multipa55
      - KEYCLOAK_IMPORT=/tmp/test-realm.json
    ports:
      - '8090:8080'