version: '3.7'
services:
  tracing-service:
    image: jaegertracing/all-in-one@sha256:aa49be5a3c80f540aa25b26073f70da2bbd71a57dcaff8765c818e712d271ccf
    ports:
      - '14268:14268'
      - '16686:16686'
  dbms-service:
    image: postgres:12.2@sha256:c52d4eac43883c53113cee0ebd1ce0fe53ef0604708822901ecca6655968fa9a
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=G4nd4lf
      - POSTGRES_PASSWORD=Mell0n
      - POSTGRES_DB=postgres
    ports:
      - '15432:5432'
  oidc-service:
    image: jboss/keycloak:9.0.3@sha256:e327b52ed4dbdb1875250d6eaed803d7a5453d0ca3e8f2a35b662499293d684c
    volumes:
      - ./keycloak/test-realm.json:/tmp/test-realm.json
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=dbms-service
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_DATABASE=keycloak
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_USER=5Element
      - KEYCLOAK_PASSWORD=multipa55
      - KEYCLOAK_IMPORT=/tmp/test-realm.json
    ports:
      - '8090:8080'
    depends_on:
      - dbms-service
  language-service:
    image: rpg/language-service
    environment:
      - JAVA_TOOL_OPTIONS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000'
      - DB_HOST=dbms-service
      - ENABLE_TRACING=false
      - TRACING_ENDPOINT=http://tracing-service:14268/api/traces
      - HTTP_PORT=8080
      - OIDC_SERVER_URL=http://oidc-service:8080/auth
    ports:
      - '8080:8080'
      - '5000:5000'
    depends_on:
      - dbms-service
      - oidc-service
  user-service:
    image: rpg/user-service
    environment:
      - JAVA_TOOL_OPTIONS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000'
      - DB_HOST=dbms-service
      - ENABLE_TRACING=false
      - TRACING_ENDPOINT=http://tracing-service:14268/api/traces
      - HTTP_PORT=8080
      - OIDC_SERVER_URL=http://oidc-service:8080/auth
      - LANGUAGE_SERVICE_URL=http://language-service:8080
    ports:
      - '8081:8080'
      - '5001:5000'
    depends_on:
      - dbms-service
      - oidc-service
      - language-service
  frontend:
    image: rpg/frontend
    depends_on:
      - dbms-service
      - oidc-service
      - language-service
      - user-service
    ports:
      - '4200:80'