version: '3.7'
services:
  dbms-service:
    image: postgres:12.2@sha256:c52d4eac43883c53113cee0ebd1ce0fe53ef0604708822901ecca6655968fa9a
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=G4nd4lf
      - POSTGRES_PASSWORD=Mell0n
      - POSTGRES_DB=postgres
    ports:
      - '15432:5432'
  oidc-service:
    image: jboss/keycloak:9.0.3@sha256:e327b52ed4dbdb1875250d6eaed803d7a5453d0ca3e8f2a35b662499293d684c
    volumes:
      - ./keycloak/test-realm.json:/tmp/test-realm.json
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=dbms-service
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_DATABASE=keycloak
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_USER=5Element
      - KEYCLOAK_PASSWORD=multipa55
      - KEYCLOAK_IMPORT=/tmp/test-realm.json
    ports:
      - '8090:8080'
    depends_on:
      - dbms-service
  language-service:
    image: rpg/language-service
    environment:
      - DB_HOST=dbms-service
      - HTTP_PORT=8080
      - OAUTH2_SERVER_URL=http://oidc-service:8080/auth
    ports:
      - '8080:8080'
    depends_on:
      - dbms-service
      - oidc-service
  user-service:
    image: rpg/user-service
    environment:
      - DB_HOST=dbms-service
      - HTTP_PORT=8080
      - OAUTH2_SERVER_URL=http://oidc-service:8080/auth
      - URL_LANGUAGE_MS=http://language-service:8080
    ports:
      - '8081:8080'
    depends_on:
      - dbms-service
      - oidc-service
      - language-service