version: '3.7'
services:
  postgres:
    image: postgres:12.2@sha256:c52d4eac43883c53113cee0ebd1ce0fe53ef0604708822901ecca6655968fa9a
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=G4nd4lf
      - POSTGRES_PASSWORD=Mell0n
      - POSTGRES_DB=postgres
    ports:
      - '15432:5432'
  keycloak:
    image: jboss/keycloak:9.0.2@sha256:4d1013ff0a26d535140374a667a82da7a0271413d4efe283ff0bf1c6055d9ab9
    volumes:
      - ./keycloak/test-realm.json:/tmp/test-realm.json
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_DATABASE=keycloak
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_USER=5Element
      - KEYCLOAK_PASSWORD=multipa55
      - KEYCLOAK_IMPORT=/tmp/test-realm.json
    ports:
      - '8090:8080'
    depends_on:
      - postgres