@startuml

entity user {
    id: UUID (PostgreSQL) or BINARY(16) (MySQL)
    \tCONSTRAINT user_pk_id PRIMARY KEY
    created_utc: TIMESTAMP NOT NULL
    \tDEFAULT NOW()
    ==
    name: VARCHAR(255) NOT NULL
    \tCONSTRAINT user_unique_name UNIQUE
    email: VARCHAR(255) NOT NULL
    \tCONSTRAINT user_unique_email UNIQUE
    displayName: VARCHAR(255)
    first_name: VARCHAR(255)
    last_name: VARCHAR(255)
    preferredLanguage: UUID NOT NULL
    \tCONSTRAINT user_fk_language
    \t\tREFERENCES language(id)
    \tDEFAULT (id of english)
    birthday: DATE
    bio: TEXT
    hours_played: INT NOT NULL
    avatar: BYTEA (PostgreSQL) or BLOB (MySQL)
    ---
    ---
    INDEX user_index_language
    \tON user USING BTREE(language)
}

entity language {
    id: UUID (PostgreSQL) or BINARY(16) (MySQL)
    \tCONSTRAINT language_pk_id PRIMARY KEY
    created_utc: TIMESTAMP NOT NULL
    \tDEFAULT NOW()
    ==
    name: VARCHAR(255) NOT NULL
    \tCONSTRAINT language_unique_name UNIQUE
    code: VARCHAR(2) NOT NULL
}

user }|--|| language

@enduml