@startuml

entity user {
    id: UUID (PostgreSQL) or BINARY(16) (MySQL)
    \tCONSTRAINT user_pk_id PRIMARY KEY
    ===
    name: VARCHAR(255) NOT NULL
    \tCONSTRAINT user_unique_name UNIQUE
    email: VARCHAR(255) NOT NULL
    \tCONSTRAINT user_unique_email UNIQUE
    created_utc: TIMESTAMP NOT NULL
    displayName: VARCHAR(255)
    first_name: VARCHAR(255)
    last_name: VARCHAR(255)
    preferredLanguage: UUID NOT NULL
    \tCONSTRAINT user_fk_language
    \t\tREFERENCES language(id) NOT NULL
    \tDEFAULT (id of en_US)
    birthday: DATE
    bio: TEXT
    hours_played: INT NOT NULL DEFAULT 0
    avatar: BYTEA (PostgreSQL) or BLOB (MySQL)
    ---
    ---
    INDEX user_index_name
    \tON user USING BTREE(name)
    INDEX user_index_language
    \tON user USING BTREE(language)
}

entity language {
    id: UUID (PostgreSQL) or BINARY(16) (MySQL)
    \tCONSTRAINT language_pk_id PRIMARY KEY
    ==
    tag: VARCHAR(5) NOT NULL
    name: VARCHAR(255) NOT NULL
    \tCONSTRAINT language_unique_name UNIQUE
    ---
    ---
    INDEX language_idx_tag
    \tON language USING BTREE(tag)
}

user }|--|| language

@enduml