@startuml

package domain {

    class User {
        {field} - name: String [0-9a-zA-z\-]+ unmodifiable <<ID>>
        {field} - email: String
        {field} - created: Instant unmodifiable
        {field} - displayName: String nullable
        {field} - firstName: String nullable
        {field} - lastName: String nullable
        {field} - preferredLanguage: Language
        {field} - birthDay: LocalDate nullable
        {field} - bio: String nullable
        {field} - hoursPlayed: int not negative
        {field} - avatar: tbd nullable
        ---
        {method}+ getters
        {method}+ equals(...): boolean
    }

    class Language {
        value type
        ===
        {field} - tag: String [a-z]{2}(?:-[A-Z]{2})?da unmodifiable <<ID>>
        {field} - name: String [0-9a-zA-z\-]+ unmodifiable
        ---
        {method} + getters
        {method} + equals(...): boolean
    }
}

package persistence {

    abstract class PersistenceEntity {
        {field} - id: UUID unmodifiable
        ---
        {method} + getId(): UUID
    }

    class PersistenceUser {
        {field} - name: String [0-9a-zA-z\-]+ unmodifiable
        {field} - email: String
        {field} - created: Instant unmodifiable
        {field} - displayName: String nullable
        {field} - firstName: String nullable
        {field} - lastName: String nullable
        {field} - preferredLanguage: Language
        {field} - birthDay: LocalDate nullable
        {field} - bio: String nullable
        {field} - hoursPlayed: int not negative
        {field} - avatar: tbd nullable
        ---
        {method}+ getters
    }

    class PersistenceLanguage {
        {field} - tag: String [a-z]{2}(?:-[A-Z]{2})? unmodifiable
        {field} - name: String [0-9a-zA-z\-]+ unmodifiable
        ---
        {method} + getters
    }

}

User "each" o-down- "one" Language:  has

PersistenceEntity <|-- PersistenceUser
PersistenceEntity <|-- PersistenceLanguage
PersistenceUser "each" o-- "one" PersistenceLanguage: has


PersistenceUser <-left-> User: maps to
PersistenceLanguage <-left-> Language: maps to

@enduml