quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:rpg_language}
    password: ${DB_PASSWORD:rpg_language}
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:language}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
  hibernate-orm:
    database:
      generation: none